<?php
/**
 * Generated by yentu on 25th August, 2014 14:30:13
 */
// Schemata
$this->table('audit_trail_data')
    ->column('audit_trail_data_id')->type('integer')->nulls(false)
    ->column('audit_trail_id')->type('integer')->nulls(false)
    ->column('data')->type('text')->nulls(true)
    ->primaryKey('audit_trail_data_id')->name('audit_trail_data_id_pk')
    ->autoIncrement()
    ;

$this->table('keystore')
    ->column('keystore_id')->type('integer')->nulls(false)
    ->column('key')->type('string')->nulls(false)->length(255)
    ->column('value')->type('text')->nulls(true)
    ->primaryKey('keystore_id')->name('keystore_pkey')
    ->autoIncrement()
    ->unique('key')->name('keystore_key_key')
    ;

$this->table('api_keys')
    ->column('api_key_id')->type('integer')->nulls(false)
    ->column('user_id')->type('integer')->nulls(false)
    ->column('active')->type('boolean')->nulls(false)
    ->column('key')->type('string')->nulls(false)->length(512)
    ->column('secret')->type('string')->nulls(false)->length(512)
    ->primaryKey('api_key_id')->name('api_keys_pkey')
    ->autoIncrement()
    ;

$this->table('audit_trail')
    ->column('audit_trail_id')->type('integer')->nulls(false)
    ->column('user_id')->type('integer')->nulls(false)
    ->column('item_id')->type('integer')->nulls(false)
    ->column('item_type')->type('string')->nulls(false)->length(64)
    ->column('description')->type('string')->nulls(false)->length(4000)
    ->column('audit_date')->type('timestamp')->nulls(false)
    ->column('type')->type('double')->nulls(false)
    ->column('data')->type('text')->nulls(true)
    ->primaryKey('audit_trail_id')->name('audit_trail_audit_id_pk')
    ->autoIncrement()
    ->index('item_id')->name('audit_trail_item_id_idx')
    ->index('item_type')->name('audit_trail_item_type_idx')
    ;

$this->table('permissions')
    ->column('permission_id')->type('integer')->nulls(false)
    ->column('role_id')->type('integer')->nulls(false)
    ->column('permission')->type('string')->nulls(true)->length(4000)
    ->column('value')->type('double')->nulls(false)
    ->column('module')->type('string')->nulls(true)->length(4000)
    ->primaryKey('permission_id')->name('perm_id_pk')
    ->autoIncrement()
    ;

$this->table('roles')
    ->column('role_id')->type('integer')->nulls(false)
    ->column('role_name')->type('string')->nulls(true)->length(64)
    ->primaryKey('role_id')->name('role_id_pk')
    ->autoIncrement()
    ;

$this->table('users')
    ->column('user_id')->type('integer')->nulls(false)
    ->column('user_name')->type('string')->nulls(false)->length(64)
    ->column('password')->type('string')->nulls(false)->length(64)
    ->column('role_id')->type('integer')->nulls(true)
    ->column('first_name')->type('string')->nulls(false)->length(64)
    ->column('last_name')->type('string')->nulls(false)->length(64)
    ->column('other_names')->type('string')->nulls(true)->length(64)
    ->column('user_status')->type('double')->nulls(true)->defaultValue("2")
    ->column('email')->type('string')->nulls(false)->length(64)
    ->primaryKey('user_id')->name('user_id_pk')
    ->autoIncrement()
    ->unique('user_name')->name('user_name_uk')
    ;

$this->table('api_keys')
    ->foreignKey('user_id')
    ->references($this->reftable('users'))
    ->columns('user_id')
    ->onDelete('NO ACTION')
    ->onUpdate('NO ACTION')
    ->name('api_keys_user_id_fkey');

$this->table('audit_trail')
    ->foreignKey('user_id')
    ->references($this->reftable('users'))
    ->columns('user_id')
    ->onDelete('SET NULL')
    ->onUpdate('NO ACTION')
    ->name('audit_trail_user_id_fk');

$this->table('permissions')
    ->foreignKey('role_id')
    ->references($this->reftable('roles'))
    ->columns('role_id')
    ->onDelete('CASCADE')
    ->onUpdate('NO ACTION')
    ->name('permissios_role_id_fk');

$this->table('users')
    ->foreignKey('role_id')
    ->references($this->reftable('roles'))
    ->columns('role_id')
    ->onDelete('SET NULL')
    ->onUpdate('NO ACTION')
    ->name('users_role_id_fk');

