#tools:
#    php_sim: true
#    php_pdepend: true
#    php_analyzer: true
#    external_code_coverage:
#        timeout: 1200    # Timeout in seconds.    
#        runs: 3
build:
  image: default-bionic
  environment:
      php: 8.3.0    
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
    excluded_paths: [bin/*, tests/*]

checks:
    php: true