<?xml version="1.0" encoding="UTF-8"?>
<project name="Yentu Migration Tool" default="package" basedir="." description="Database migration tool">
    
    <property name="build.dir" value="./build"/>
    <property name="php.path" value="${php.interpreter}" override="false" />
    <exec command="which composer" outputProperty="system.composer" checkreturn="false" />
    <property name="php.composer" value="${system.composer}" override="false" />
    <property name="build.version" value="dev" />
    
    <target name="clean">
        <delete dir="${build.dir}" />
    </target>
    <target name="package">
        <echo msg="Creating phar archive"/>
        <mkdir dir="${build.dir}" />
        <mkdir dir="${build.dir}/src" />
        <copy todir="${build.dir}/src" >
            <fileset dir="./">
                <include name="composer.json" />
                <include name="composer.lock" />
                <include name="src/**" />
                <include name="bin/**" />
            </fileset>
        </copy>
        <resolvepath propertyName = "repo.target" file="${build.dir}/src" />
        <exec command="git describe --tags" outputProperty="build.version" />
        <echo msg="#!/usr/bin/env php&#10;&lt;?php&#10;Phar::mapPhar('yentu.phar');&#10;define('PHING_BUILD_VERSION', '${build.version}');&#10;require 'phar://yentu.phar/src/main.php';&#10;__HALT_COMPILER();" file="${repo.target}/stub.php" />
        <composer command="install" php="${php.path}" composer="${php.composer}">
            <arg line="--working-dir ${repo.target}" />
            <arg line="--prefer-dist" />
            <arg line="--optimize-autoloader" />
            <arg line="--no-dev" />
        </composer>
        <pharpackage 
            stub='${repo.target}/stub.php'
            alias='yentu.phar'
            destfile='${build.dir}/yentu.phar'  
            compression='bzip2'
            basedir='${repo.target}'>
            <fileset dir='${repo.target}'>
                <include name="src/**" />
                <include name="bin/**" />
                <include name="vendor/**" />
            </fileset>
        </pharpackage>
        <chmod file="${build.dir}/yentu.phar" mode="0755" />
        <delete dir="${repo.target}" />
    </target>    
</project>