<?php

namespace yentu\tests\cases\unit;

use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\TestCase;
use yentu\CodeWriter;

#[Group('unit')]
class CodeWriterTest extends TestCase
{
    public function testAddAndLn(): void
    {
        $writer = new CodeWriter();
        $writer->add('first_line();');
        $writer->ln();
        $writer->addNoLn('partial_');
        $writer->addNoIndent('line();');
        $writer->ln();

        $output = (string) $writer;
        $this->assertStringContainsString("first_line();\n\npartial_line();\n", $output);
    }

    public function testIndentation(): void
    {
        $writer = new CodeWriter();
        $writer->add('start()');
        $writer->addIndent();
        $writer->add('->nested()');
        $writer->addIndent();
        $writer->add('->deeper()');
        $writer->decreaseIndent();
        $writer->add('->back()');
        $writer->decreaseIndent();
        $writer->add('->end();');

        $output = (string) $writer;
        $this->assertStringContainsString("start()\n    ->nested()\n        ->deeper()\n    ->back()\n->end();\n", $output);
    }

    public function testHeaderInToString(): void
    {
        $writer = new CodeWriter();
        $writer->add('// code');

        $output = (string) $writer;
        $this->assertStringStartsWith("<?php\n/**\n * Generated by yentu on ", $output);
        $this->assertStringContainsString("// code\n", $output);
    }
}
