<?php
namespace yentu;

class CodeWriter
{
    private $lines;
    private $indentation;
    
    public function __construct()
    {
        $this->add('<?php');
        $this->add('/**');
        $this->add(' * Generated by yentu on ' . date('jS F, Y H:i:s'));
        $this->add(' */');
        $this->add();
    }
    
    public function add($line = '')
    {
        $this->lines .= str_repeat(' ', $this->indentation) . "$line\n";
    }
    
    public function addNoLn($line = '')
    {
        $this->lines .= str_repeat(' ', $this->indentation) . "$line";
    }
    
    public function addNoIndent($line = '')
    {
        $this->lines .= $line;
    }
    
    public function ln()
    {
        $this->lines .= "\n";
    }

    
    public function addIndent()
    {
        $this->indentation += 4;
    }
    
    public function decreaseIndent()
    {
        $this->indentation -= 4;
    }
    
    public function __toString()
    {
        return $this->lines;
    }
}

