name: Tests
on: [push, pull_request]
jobs:
  PHPUnit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.3', '8.4']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pdo, sqlite3, pdo_sqlite
          coverage: pcov
          tools: composer
      - name: Running composer
        run: composer install --prefer-dist --no-interaction
      - name: Running php unit tests
        run: vendor/bin/phpunit --coverage-clover coverage.clover
      - name: Downloading Ocular Tool
        continue-on-error: true
        run: composer global require scrutinizer/ocular dev-master
      - name: Uploading Code Metrics
        continue-on-error: true
        run: php ~/.composer/vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
